version: '3.8'

services:
  # NATS service
  nats:
    image: nats:2.10-alpine
    container_name: aws-nats
    command:
      - "--name=nats-server"
      - "--jetstream"
      - "--store_dir=/data"
      - "--http_port=8222"
      - "--port=4222"
      - "--max_payload=8MB"
      - "--max_pending=256MB"
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    volumes:
      - nats_data:/data
    environment:
      - NATS_JETSTREAM_MAX_MEMORY_STORE=1GB
      - NATS_JETSTREAM_MAX_FILE_STORE=10GB
    restart: unless-stopped
    networks:
      - mini-aws-network

  # MinIO S3-compatible storage
  minio:
    image: minio/minio:latest
    container_name: mycloud-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
      - MINIO_NOTIFY_WEBHOOK_ENABLE_NATS=on
      - MINIO_NOTIFY_WEBHOOK_ENDPOINT_NATS=http://mycloud-s3:3000/webhook
    restart: unless-stopped
    networks:
      - mini-aws-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # PostgreSQL
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: s3
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - mini-aws-network


volumes:
  nats_data:
    driver: local
  minio_data:
    driver: local
  pg_data:
    driver: local


networks:
  mini-aws-network:
    driver: bridge
